# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DB_URL: mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.2.12
      JWT_KEY: fsjldfkj#$dljfjdlkfjldf
      GOOGLE_CLIENT_ID: 1064512413669-lbm4tk6mojjb1c8drrlc9bb99fhbc2dh.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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
      AWS_ACCESS_KEY: AKIA47CRW2HVYSMVGLCQ
      AWS_SECRET_KEY: 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
      S3_REGION: us-east-1
      BUCKET_NAME: augbatch23233

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm test
